matrice:
  - identifier
  - owner
  - insee
  - prefix
  - section
  - number
  - locality

raw_parca:
  - idu
  - reg_name
  - reg_code
  - dep_name
  - dep_code
  - com_name
  - com_code
  - insee
  - prefix
  - section
  - number
  - locality
  - cad_area
  - source

parca:
  - identifier
  - owner
  - idu
  - reg_name
  - reg_code
  - dep_name
  - dep_code
  - com_name
  - com_code
  - insee
  - prefix
  - section
  - number
  - locality
  - gis_area
  - cad_area
  - source

ua:
  - identifier
  - owner
  - idu
  - reg_name
  - reg_code
  - dep_name
  - dep_code
  - com_name
  - com_code
  - insee
  - prefix
  - section
  - number
  - locality
  - is_wooded
  - mgmt_code
  - pcl_code
  - sub_code
  - std_type
  - std_wealth
  - std_stage
  - std_year
  - is_damaged
  - is_available
  - is_compartmented
  - res_spe1
  - res_spe2
  - res_struct
  - cop_spe1
  - cop_spe2
  - cop_density
  - cop_nature
  - reg_spe1
  - reg_spe2
  - reg_stage
  - reg_density
  - treatment
  - is_subsidized
  - subsidy
  - comment
  - soil
  - gis_area
  - cor_area
  - cad_area

vct_poly:
  - identifier
  - type
  - nature
  - name
  - source

vct_line:
  - identifier
  - type
  - nature
  - name
  - source
  - offset

vct_point:
  - identifier
  - type
  - nature
  - name
  - source
  - rotation

road_poly:
  - identifier
  - type

road_line:
  - identifier
  - type
  - nature
  - importance
  - is_private
  - restriction
  - name
  - source
  - offset

com_poly:
  - identifier
  - reg_code
  - dep_code
  - insee
  - postal
  - com_name
