identifiant:
  name: "IDENTIFIANT"
  alias: ["foret"]
  class: "character"
  definition: "Identifiant de la forêt, génrélament identique au nom"

proprietaire:
  name: "PROPRIETAIRE"
  alias: ["prop", "owner", "proprio", "proprietaire"]
  class: "character"
  definition: "Nom du propriétaire"

land_use:
  name: "LAND_USE"
  alias: ["boisee", "is_boisee", "occupation", "occup_sol"]
  class: "character"
  definition: "Occupation du sol"

# cog ----
reg_num:
  name: "REG_CODE"
  alias: ["reg", "code_insee_de_la_region"]
  class: "character"
  definition: "Code de la région selon l'INSEE"

reg_nom:
  name: "REG_NOM"
  alias: ["ncc_reg"]
  class: "character"
  definition: "Nom de la région selon l'INSEE"

dep_num:
  name: "DEP_CODE"
  alias: ["dep", "dep_code", "code_insee_du_departement"]
  class: "character"
  definition: "Code du département selon l'INSEE"

dep_nom:
  name: "DEP_NOM"
  alias: ["NCC_DEP"]
  class: "character"
  definition: "Nom du département selon l'INSEE"

com_num:
  name: "COM_CODE"
  alias: ["commune", "com"]
  class: "character"
  definition: "Code de la commune selon l'INSEE"

com_nom:
  name: "COM_NOM"
  alias: ["ncc_com", "nom_officiel"]
  class: "character"
  definition: "Nom de la commune selon l'INSEE"

insee:
  name: "INSEE"
  alias: ["insee", "code_insee"]
  class: "character"
  definition: "Code INSEE de la commune"

# com ----
postal:
  name: "POSTAL"
  alias: ["code_postal"]
  class: "character"
  definition: "Postal code of the town"

# cadastre ----
idu:
  name: "IDU"
  alias: ["idu"]
  class: "character"
  definition: "Identifiant cadastral unique"

prefix:
  name: "PREFIXE"
  alias: ["com_abs", "prefixe"]
  class: "character"
  definition: "Préfixe cadastral (3 entiers)"

section:
  name: "SECTION"
  alias: ["section"]
  class: "character"
  definition: "Section cadastrale (2 lettres ou chiffres)"

numero:
  name: "NUMERO"
  alias: ["numero", "n_parca"]
  class: "character"
  definition: "Numéro cadastral (4 entiers)"

lieu_dit:
  name: "LIEU_DIT"
  alias: ["LIEUDIT", "lieu_dit"]
  class: "character"
  definition: "Lieu-dit cadastral"

surf_cad:
  name: "SURF_CA"
  alias: ["contenance"]
  class: numeric
  definition: "Surface cadastrale (hectares)"

# surfaces ----
surf_sig:
  name: "SURF_SIG"
  class: numeric
  definition: "Surface SIG en hectares"

surf_cor:
  name: "SURF_COR"
  class: numeric
  definition: "Surface corrigée recalculée"

# ua ----
ug:
  name: "PARFOR"
  alias: ["ug"]
  class: "character"
  definition: "Unité de gestion forestière"

parcelle:
  name: "N_PARFOR"
  alias: ["PF", "PRF", "PARCELLE", "PAR"]
  class: "character"
  definition: "Parcelle forestière"

sous_parcelle:
  name: "N_SSPARFOR"
  alias: ["SSPF", "SSPRF", "SOUS_PARCELLE", "SPAR"]
  class: "character"
  definition: "Sous-parcelle forestière"

stand:
  name: "PLT_PLMT"
  alias: ["PLT_TYPE"]
  class: "character"
  definition: "Forest stand type"

wealth:
  name: "PLT_RICH"
  class: "character"
  definition: "Stand wealth"

stage:
  name: "PLT_STAD"
  class: "character"
  definition: "Stand development stage"

year:
  name: "PLT_ANNE"
  class: "character"
  definition: "Year of stand establishment"

structure:
  name: "PLT_STRU"
  alias: ["PLT_STR", "REV_CA"]
  class: "character"
  definition: "Stand reserve structure"

ess1:
  name: "ESS_1_NOM"
  alias: ["PLT_ESS", "PLT_COMS"]
  class: "character"
  definition: "Essence principale"

ess1_pct:
  name: "ESS_1_PCT"
  class: numeric
  definition: "% essence principale"

ess2:
  name: "ESS_2_NOM"
  class: "character"
  definition: "Essence secondaire"

ess2_pct:
  name: "ESS_2_PCT"
  class: numeric
  definition: "% essence secondaire"

ess3:
  name: "ESS_3_NOM"
  class: "character"
  definition: "Essence tertiaire"

ess3_pct:
  name: "ESS_3_PCT"
  class: numeric
  definition: "% essence tertiaire"

taillis:
  name: "TSE_DSCR"
  class: "character"
  definition: "Taillis ou sous-étage"

regeneration:
  name: "REG_DSCR"
  class: "character"
  definition: "Régénération"

comment:
  name: "COMMENTS"
  class: "character"
  definition: "Commentaires"

sol:
  name: "SOL_TYPE"
  alias: ["GEOL_TYPE"]
  class: "character"
  definition: "Type de station forestière"

amenagement:
  name: "AME_TYPE"
  class: "character"
  definition: "Traitement retenu par le gestionnaire"

dispositif:
  name: "DISPOSITIF"
  class: "character"
  definition: "..."

# vector ----
source:
  name: "SOURCE"
  class: "character"
  definition: "Source from which the data comes"

type:
  name: "TYPE"
  class: "character"
  definition: "Acronym used in SEQUOIA process"

nature:
  name: "NATURE"
  alias: ["nature"]
  class: "character"
  definition: "Nature from IGN BDTopo"

name:
  name: "NAME"
  alias: ["NOM"]
  class: "character"
  definition: "Name from IGN BDTopo"

offset:
  name: "OFFSET"
  alias: ["DECA"]
  class: "character"
  definition: "Offset used in SEQUOIA process"

rotation:
  name: "ROTATION"
  alias: ["ROT"]
  class: "character"
  definition: "Rotation used in SEQUOIA process"

# road ----
importance:
  name: "IMPORTANCE"
  alias: ["importance"]
  class: "integer"
  definition: "Importance from IGN BDTopo"

private:
  name: "PRIVATE"
  alias: ["prive"]
  class: "boolean"
  definition: "Private from IGN BDTopo"

restriction:
  name: "RESTRICTION"
  alias: ["restriction_de_poids_total"]
  class: "character"
  definition: "Weight restriction from IGN BDTopo"
