matrice:
  - identifier
  - owner
  - insee
  - prefix
  - section
  - number
  - locality

raw_parca:
  - idu
  - reg_name
  - reg_code
  - dep_name
  - dep_code
  - com_name
  - com_code
  - prefix
  - section
  - number
  - locality
  - cad_area
  - source

parca:
  - identifier
  - owner
  - idu
  - reg_name
  - reg_code
  - dep_name
  - dep_code
  - com_name
  - com_code
  - insee
  - prefix
  - section
  - number
  - locality
  - cad_area
  - source

ua:
  - identifier
  - owner
  - idu
  - reg_name
  - reg_code
  - dep_name
  - dep_code
  - com_name
  - com_code
  - insee
  - prefix
  - section
  - number
  - locality
  - land_use
  - mgmt_code
  - pcl_code
  - sub_code
  - stand
  - wealth
  - stage
  - year
  - structure
  - spe1
  - spe1_pct
  - spe2
  - spe2_pct
  - spe3
  - spe3_pct
  - copice
  - rege
  - soil
  - treatment
  - is_subsidized
  - subsidy
  - comment
  - gis_area
  - cor_area
  - cad_area

vct_poly:
  - identifier
  - type
  - nature
  - name
  - source

vct_line:
  - identifier
  - type
  - nature
  - name
  - source
  - offset

vct_point:
  - identifier
  - type
  - nature
  - name
  - source
  - rotation

road_line:
  - identifier
  - type
  - nature
  - importance
  - is_private
  - restriction
  - name
  - source
  - offset

com_poly:
  - identifier
  - reg_code
  - dep_code
  - insee
  - postal
  - com_name
