identifier:
  name: "IDENTIFIANT"
  alias: ["foret"]
  class: "character"
  definition: "Forest identifier"

owner:
  name: "PROPRIETAIRE"
  alias: ["prop", "owner", "proprio", "proprietaire"]
  class: "character"
  definition: "Owner name"

is_wooded:
  name: "BOISE"
  alias: ["boisee", "is_boisee", "occupation", "occup_sol"]
  class: "boolean"
  definition: "Land use field specific for forest"

# cog ----
reg_code:
  name: "REG_CODE"
  alias: ["reg", "code_insee_de_la_region"]
  class: "character"
  definition: "Region INSEE code"

reg_name:
  name: "REG_NOM"
  alias: ["ncc_reg"]
  class: "character"
  definition: "Region INSEE name"

dep_code:
  name: "DEP_CODE"
  alias: ["dep", "dep_code", "code_insee_du_departement"]
  class: "character"
  definition: "Department INSEE code"

dep_name:
  name: "DEP_NOM"
  alias: ["NCC_DEP"]
  class: "character"
  definition: "Department INSEE name"

com_code:
  name: "COM_CODE"
  alias: ["commune", "com"]
  class: "character"
  definition: "Town INSEE code"

com_name:
  name: "COM_NOM"
  alias: ["ncc_com", "nom_officiel"]
  class: "character"
  definition: "Town INSEE name"

insee:
  name: "INSEE"
  alias: ["insee", "code_insee"]
  class: "character"
  definition: "Town full INSEE code"

# com ----
postal:
  name: "POSTAL"
  alias: ["code_postal"]
  class: "character"
  definition: "Postal town code"

# cadastre ----
idu:
  name: "IDU"
  alias: ["idu"]
  class: "character"
  definition: "Unique cadastral identifier"

prefix:
  name: "PREFIXE"
  alias: ["com_abs", "prefixe"]
  class: "character"
  definition: "Cadastral prefix code (3 integer)"

section:
  name: "SECTION"
  alias: ["section"]
  class: "character"
  definition: "Cadastral section code (2 character or integer)"

number:
  name: "NUMERO"
  alias: ["numero", "n_parca"]
  class: "character"
  definition: "Cadastral number code(4 integer)"

locality:
  name: "LIEU_DIT"
  alias: ["LIEUDIT", "lieu_dit"]
  class: "character"
  definition: "Locality / called place"

cad_area:
  name: "SURF_CAD"
  alias: ["contenance", "SURF_CA"]
  class: numeric
  definition: "Cadastral area (hectares)"

# surfaces ----
gis_area:
  name: "SURF_SIG"
  class: numeric
  definition: "GIS area (hectares)"

cor_area:
  name: "SURF_COR"
  class: numeric
  definition: "Cadastral corrected area (hectares)"

# ua ----
mgmt_code:
  name: "PARFOR"
  alias: ["ug"]
  class: "character"
  definition: "Management unit code"

pcl_code:
  name: "N_PARFOR"
  alias: ["PF", "PRF", "PARCELLE", "PAR"]
  class: "character"
  definition: "Parcel unit code"

sub_code:
  name: "N_SSPARFOR"
  alias: ["SSPF", "SSPRF", "SOUS_PARCELLE", "SPAR"]
  class: "character"
  definition: "Sub-parcel unit code"

stand:
  name: "PLT_PLMT"
  alias: ["PLT_TYPE"]
  class: "character"
  definition: "Forest stand type"

wealth:
  name: "PLT_RICH"
  class: "character"
  definition: "Stand wealth"

stage:
  name: "PLT_STAD"
  class: "character"
  definition: "Stand development stage"

year:
  name: "PLT_ANNE"
  class: "character"
  definition: "Year of stand establishment"

structure:
  name: "PLT_STRU"
  alias: ["PLT_STR", "REV_CA"]
  class: "character"
  definition: "Stand reserve structure"

spe1:
  name: "ESS_1_NOM"
  alias: ["PLT_ESS", "PLT_COMS"]
  class: "character"
  definition: "Main specie"

spe1_pct:
  name: "ESS_1_PCT"
  class: numeric
  definition: "% main specie"

spe2:
  name: "ESS_2_NOM"
  class: "character"
  definition: "Secondary specie"

spe2_pct:
  name: "ESS_2_PCT"
  class: numeric
  definition: "% secondary specie"

spe3:
  name: "ESS_3_NOM"
  class: "character"
  definition: "Tertiary essence"

spe3_pct:
  name: "ESS_3_PCT"
  class: numeric
  definition: "% tertiary essence"

copice:
  name: "TSE_DSCR"
  class: "character"
  definition: "Copice"

regeneration:
  name: "REG_DSCR"
  class: "character"
  definition: "Regeneration"

comment:
  name: "COMMENTS"
  class: "character"
  definition: "Comments"

soil:
  name: "SOL_TYPE"
  alias: ["GEOL_TYPE"]
  class: "character"
  definition: "Soil classification"

treatment:
  name: "AME_TYPE"
  class: "character"
  definition: "Treatment chosen by the forest manager"

is_subsidized:
  name: "SUBVENTIONNE"
  class: "boolean"
  definition: "Is subsidized ?"

subsidy:
  name: "SUBVENTION"
  alias: ["DISP_TYPE"]
  class: "character"
  definition: "Subsidy scheme"

# vector ----
source:
  name: "SOURCE"
  class: "character"
  definition: "Source from which the data comes"

type:
  name: "TYPE"
  class: "character"
  definition: "Acronym used in SEQUOIA process"

nature:
  name: "NATURE"
  alias: ["nature"]
  class: "character"
  definition: "Nature from IGN BDTopo"

name:
  name: "NOM"
  class: "character"
  definition: "Name from IGN BDTopo"

offset:
  name: "DECALAGE"
  alias: ["DECA"]
  class: "character"
  definition: "Offset used in SEQUOIA process"

rotation:
  name: "ROTATION"
  alias: ["ROT"]
  class: "character"
  definition: "Rotation used in SEQUOIA process"

# road ----
importance:
  name: "IMPORTANCE"
  alias: ["importance"]
  class: "integer"
  definition: "Importance from IGN BDTopo"

is_private:
  name: "PRIVE"
  alias: ["prive"]
  class: "boolean"
  definition: "Private from IGN BDTopo"

restriction:
  name: "RESTRICTION"
  alias: ["restriction_de_poids_total"]
  class: "character"
  definition: "Weight restriction from IGN BDTopo"
