namespace:
  v.seq: "sequoia"
  v.com: "vectoriel"
  v.cad: "cadastre"
  v.sol: "sol"
  v.pat: "patrimoine"
  v.gpu: "urbanisme"
  v.mnhn: "environnement"
  v.road: "vectoriel"
  v.ifn: "ifn"
  v.infra: "vectoriel"
  v.vege: "vectoriel"
  v.hydro: "vectoriel"
  v.toponyme: "vectoriel"
  v.curves: "vectoriel"
  v.access: "access"
  v.prsf: "vectoriel"
  v.old: "vector"
  r.alt: "altimetrie"
  r.ortho: "imagerie"
  r.scan: "scan"
  r.sol: "sol"

path:
  sequoia: "1_SEQUOIA"
  vector: "2_VECTOR"
  vectoriel: "2_VECTOR/VECTORIEL"
  cadastre: "2_VECTOR/CADASTRE"
  sol: "2_VECTOR/SOL"
  access: "2_VECTOR/ACCESS"
  patrimoine: "2_VECTOR/PATRIMOINE"
  urbanisme: "2_VECTOR/URBANISME"
  environnement: "2_VECTOR/ENVIRONNEMENT"
  ifn: "2_VECTOR/IFN"
  scan: "3_RASTER/SCAN"
  altimetrie: "3_RASTER/ALTIMETRIE"
  imagerie: "3_RASTER/IMAGERIE"
