matrice:
  - identifiant
  - proprietaire
  - insee
  - prefix
  - section
  - numero
  - lieu_dit

raw_parca:
  - idu
  - reg_nom
  - reg_num
  - dep_nom
  - dep_num
  - com_nom
  - com_num
  - prefix
  - section
  - numero
  - lieu_dit
  - surf_cad

parca:
  - identifiant
  - proprietaire
  - idu
  - reg_nom
  - reg_num
  - dep_nom
  - dep_num
  - com_nom
  - com_num
  - prefix
  - section
  - numero
  - lieu_dit
  - surf_cad

ua:
  - identifiant
  - proprietaire
  - idu
  - reg_nom
  - reg_num
  - dep_nom
  - dep_num
  - com_nom
  - com_num
  - prefix
  - section
  - numero
  - lieu_dit
  - land_use
  - ug
  - parcelle
  - sous_parcelle
  - peuplement
  - richesse
  - stade
  - annee
  - structure
  - ess1
  - ess1_pct
  - ess2
  - ess2_pct
  - ess3
  - ess3_pct
  - taillis
  - rege
  - sol
  - amenagement
  - dispositif
  - comment
  - surf_sig
  - surf_cor
  - surf_cad

vct_poly:
  - type
  - nature
  - name

vct_line:
  - type
  - nature
  - name
  - offset

vct_point:
  - type
  - nature
  - name
  - rotation
