matrice:
  - identifiant
  - proprietaire
  - insee
  - prefix
  - section
  - numero
  - lieu_dit

raw_parca:
  - idu
  - reg_nom
  - reg_num
  - dep_nom
  - dep_num
  - com_nom
  - com_num
  - prefix
  - section
  - numero
  - lieu_dit
  - surf_cad
  - source

parca:
  - identifiant
  - proprietaire
  - idu
  - reg_nom
  - reg_num
  - dep_nom
  - dep_num
  - com_nom
  - com_num
  - insee
  - prefix
  - section
  - numero
  - lieu_dit
  - surf_cad
  - source

ua:
  - identifiant
  - proprietaire
  - idu
  - reg_nom
  - reg_num
  - dep_nom
  - dep_num
  - com_nom
  - com_num
  - insee
  - prefix
  - section
  - numero
  - lieu_dit
  - land_use
  - ug
  - parcelle
  - sous_parcelle
  - stand
  - wealth
  - stage
  - year
  - structure
  - ess1
  - ess1_pct
  - ess2
  - ess2_pct
  - ess3
  - ess3_pct
  - taillis
  - rege
  - sol
  - amenagement
  - dispositif
  - comment
  - surf_sig
  - surf_cor
  - surf_cad

vct_poly:
  - identifiant
  - type
  - nature
  - name
  - source

vct_line:
  - identifiant
  - type
  - nature
  - name
  - source
  - offset

vct_point:
  - identifiant
  - type
  - nature
  - name
  - source
  - rotation

road_line:
  - identifiant
  - type
  - nature
  - importance
  - private
  - restriction
  - name
  - source
  - offset

com_poly:
  - identifiant
  - reg_num
  - dep_num
  - insee
  - postal
  - com_nom
